### ISSUE TITLE
Bower fails to install lightbox2

### ISSUE THREAD

**Issue by monecchi** [lokesh/lightbox2#586]
I'm trying to install **lightbox2** with Bower, but it fails. I'm able to install any other package, so no issues with bower config. I'd really  appreciate any inputs regarding this issue.

`bower install lightbox2 --save`

#### This is the terminal response

```
bower not-cached    https://github.com/lokesh/lightbox2.git#*
bower resolve       https://github.com/lokesh/lightbox2.git#*
bower download      https://github.com/lokesh/lightbox2/archive/v2.9.0.tar.gz
bower extract       lightbox2#* archive.tar.gz
bower invalid-meta  for:/var/folders/t3/lrrqhsh93s33gmwvfk8xlv0r0000gn/T/User/bower/a08e0fb2a5ef407322a40916669bdd9d-24812-qnTvTV/bower.json
bower invalid-meta  The "main" field cannot contain font, image, audio, or video files
bower invalid-meta  The "main" field cannot contain font, image, audio, or video files
bower invalid-meta  The "main" field cannot contain font, image, audio, or video files
bower invalid-meta  The "main" field cannot contain font, image, audio, or video files
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .png files: ["./dist/images/close.png","./dist/images/next.png","./dist/images/prev.png"]
bower resolved      https://github.com/lokesh/lightbox2.git#2.9.0
bower not-cached    https://github.com/jquery/jquery-dist.git#~2
bower resolve       https://github.com/jquery/jquery-dist.git#~2
bower download      https://github.com/jquery/jquery-dist/archive/2.2.4.tar.gz
bower extract       jquery#~2 archive.tar.gz
bower EACCES        EACCES: permission denied, rename '/var/folders/t3/lrrqhsh93s33gmwvfk8xlv0r0000gn/T/User/bower/d223e1439188e478349d52476506c22e-24812-3L4Iuh' -> '/Users/User/.cache/bower/packages/35300e45e44dbc6f186ed069533ef0af/2.2.4'

Stack trace:
Error: EACCES: permission denied, rename '/var/folders/t3/lrrqhsh93s33gmwvfk8xlv0r0000gn/T/User/bower/d223e1439188e478349d52476506c22e-24812-3L4Iuh' -> '/Users/User/.cache/bower/packages/35300e45e44dbc6f186ed069533ef0af/2.2.4'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.3.1
OS: Darwin 16.5.0 x64
```

**Comment by lokesh** [comment]
Fix queued up in `dev` branch. I'll release this shortly.

**Comment by lokesh** [comment]
Resolved: https://github.com/lokesh/lightbox2/releases/tag/v2.10.0
